apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharma-deployer-binding
  namespace: dev
  labels:
    env: dev
    managed-by: terraform
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-runner
roleRef:
  kind: Role
  name: pharma-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharma-deployer-binding
  namespace: qa
  labels:
    env: qa
    managed-by: terraform
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-runner
roleRef:
  kind: Role
  name: pharma-deployer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharma-deployer-binding
  namespace: prod
  labels:
    env: prod
    managed-by: terraform
subjects:
  - kind: ServiceAccount
    name: gitlab-runner
    namespace: gitlab-runner
roleRef:
  kind: Role
  name: pharma-deployer
  apiGroup: rbac.authorization.k8s.io
